### ISSUE TITLE
Your python-alsaaudio installation does not support the needed DSD sample format

### ISSUE THREAD

**Issue by afalout** [lintweaker/python-dsd-tools#2]
Fedora 23, Python 2.7.10

I checked out the git, and rebuild RPM:

cd python-dsd-tools/

[push2dev.local python-dsd-tools]# git pull
remote: Counting objects: 12, done.
remote: Total 12 (delta 3), reused 3 (delta 3), pack-reused 9
Unpacking objects: 100% (12/12), done.
From http://github.com/lintweaker/python-dsd-tools
   b904eef..7c190d8  master     -> origin/master
Updating b904eef..7c190d8
Fast-forward
 playdsd.py                                            | 9 ++++++---
 pyalsaaudio-patches/pyalsaaudio-add-dsd-formats.patch | 9 +++++----
 2 files changed, 11 insertions(+), 7 deletions(-)

[push2dev.local python-dsd-tools]# rpm -ivh SRPMS/python-alsaaudio-0.7-8.fc20.src.rpm
Updating / installing...
   1:python-alsaaudio-0.7-8.fc20      warning: user kramer does not exist - using root
warning: group kramer does not exist - using root
warning: user kramer does not exist - using root
warning: group kramer does not exist - using root
warning: user kramer does not exist - using root
warning: group kramer does not exist - using root
###### ########################### [100%]

[push2dev.local python-dsd-tools]# cd ~/rpmbuild/SPECS
[push2dev.local SPECS]# rpmbuild -bb --target=$(uname -m) python-alsaaudio.spec
Building target platforms: i686
Building for target i686
...etc...
Wrote: /root/rpmbuild/RPMS/i686/python-alsaaudio-0.7-8.fc23.i686.rpm
Wrote: /root/rpmbuild/RPMS/i686/python-alsaaudio-debuginfo-0.7-8.fc23.i686.rpm
..etc..

[push2dev.local SPECS]# dnf reinstall /root/rpmbuild/RPMS/i686/python-alsaaudio-0.7-8.fc23.i686.rpm
Last metadata expiration check performed 0:25:25 ago on Sat Nov 28 16:12:10 2015.
Dependencies resolved.
...etc...
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Reinstalling: python-alsaaudio-0.7-8.fc23.i686                                                                                           1/2 
  Erasing     : python-alsaaudio-0.7-8.fc23.i686                                                                                           2/2 
  Verifying   : python-alsaaudio-0.7-8.fc23.i686                                                                                           1/2 
  Verifying   : python-alsaaudio-0.7-8.fc23.i686                                                                                           2/2 

Reinstalled:
  python-alsaaudio.i686 0.7-8.fc23                                                                                                             

Complete!
[push2dev.local SPECS]# cd -
/storage/usr-src/nativeDSD/python-dsd-tools

[push2dev.local python-dsd-tools]# ./playdsd.py -c 0
Your python-alsaaudio installation does not support the needed DSD sample format

Am I doing something wrong?

Thanks!

**Comment by lintweaker** [comment]
I am not sure what you are doing wrong. I just a build on F23 myself, it works just fine. I have added a F23 SRPM for your convenience.

**Comment by lintweaker** [comment]
BTW as you have/had problems compiling the kernel, you probably do not have a device that support DSD yet. You can try with './playdsd.py -l':

./playdsd.py -l

Available sound cards:

'Intel'     : Not a (UAC2) USB sound card
'HDDAC1'    : USB device with native DSD support

**Comment by afalout** [comment]
Thanks for you reply; unfortunately this did not work either:

./playdsd.py -l
Your python-alsaaudio installation does not support the needed DSD sample format

Is this message perhaps stating:

"Your SYSTEM does not support the needed DSD sample format"?

Meaning that, regardless of "python-alsaaudio installation", this wont work unless both kernel and alsa support DSD sample format?

Thanks!

**Comment by lintweaker** [comment]
The message means that the Python ALSA module does not have the DSD sample format support. Fedora 23 has a kernel and ALSA with DSD support, so no problem there.
You are using a 32-bit system, I'll setup a F23 32-bit system to see If I can recreate the issue.

**Comment by lintweaker** [comment]
Tested on a clean F23 32-bit system, works great. I have added a 32-bit RPM for your convenience.

**Comment by afalout** [comment]
Thank you VERY much for the RPM - it worked!

Only difference I noted is the version difference - I used your old version of SRPM to rebuild RPM (python-alsaaudio-0.7-8.fc20.src.rpm) But RPM you provided and that does work is python-alsaaudio-0.7-9.fc23.src.rpm

In any case - solved. Thank you again for your help!

**Comment by lintweaker** [comment]
Great, the build number update 0.7-8 -> 0.7-9 is to indicate that it is a updated version from the original package.
